#!usr/bin/env python3

#python problem set 3
#Q1 counting A & T

dna = 'GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTCCCCTGCCCTCAACAAGATGTTTTGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACACCCCCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGCCCCCACCATGAGCGCTGCTCAGATAGCGATGGTCTGGCCCCTCCTCAGCATCTTATCCGAGTGGAAGGAAATTTGCGTGTGGAGTATTTGGATGACAGAAACACTTTTCG'
print ('The DNA sequence is',dna)

A = dna.count ('A')
T = dna.count ('T')
print ('A =', A)
print ('T =', T)

#Q2 percentage GC

total_count = dna.count ('A') + dna.count ('T') + dna.count ('C') + dna.count ('G')

percent_GC_content = '{:.1%}'.format ((dna.count ('G') + dna.count ('C')) / total_count)

print ('The GC percentage is',percent_GC_content)

#Q3 reverse complement; remember to complement first!

compT2a = dna.replace ('T', 'a')
compA2t = compT2a.replace ('A', 't')
compG2c = compA2t.replace ('G', 'c')
compC2g = compG2c.replace ('C', 'g')

rev = compC2g [::-1]
print ('The reverse complement of the DNA sequence is:\n',rev)



